<?php

namespace Tests\Unit;

use App\Models\Item;
use App\Models\User;
use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;

class ItemTest extends TestCase
{
    use RefreshDatabase;

    private $user, $item;
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->user = factory(User::class)->create();

        $this->item = factory(Item::class)->create([
            'title' => "asus",
            'item_status' => "20",
        ]);

    }
    /**
     * A basic test example.
     * @test
     * @return void
     */
    public function save_item_test()
    {
        $data = $this->item->toArray();

        $response = $this->actingAs($this->user, 'api')->json('POST', '/api/auth/saveItem',$data);
//
//        $item = new Item($data);
//
////       $items = $item->toArray();
//        $item->save();

        $response->assertStatus(201);

    }
}
